config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :show]
  resource :activities, only: [:show, :create]
  get 'activities/deposit' => 'activities#depositform'
  get 'activities/payment' => 'activities#paymentform'
  post 'activites/deposit' => 'activities#create'
  post 'activites/payment' => 'activities#create'
  resource :payees
 

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :users

	validates_presence_of :desc
	validates_presence_of :kind
	validates_presence_of :amount
	validates_presence_of :user_id
end

app/models/payee.rb
class Payee < ActiveRecord::Base
	belongs_to :users
	
	validates_presence_of :name
	validates_presence_of :email
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :payees
	has_many :activities
	has_secure_password

	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
	validates_confirmation_of :password
	 validates_length_of :name, within: 4..20, too_long: 'pick a shorter name', too_short: 'pick a longer name'

  after_initialize :init

  def init
    self.balance  ||= 0.0           #will set the default value only if it's nil
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @activities = Activity.where({user_id: session[:user_id]})
  end

  def paymentform
  	@activities = User.find(session[:user_id]).activities
  	@payees = Payee.all
  end
  
  def depositform
  	@activities = User.find(session[:user_id]).activities
  end

  def create 
  	if params[:deposit]
      amount = params[:deposit].to_f
  		@activity = Activity.create(desc: params[:desc], kind: params[:kind], amount: params[:deposit], user_id: session[:user_id])
  	else
  		amount = -params[:payment].to_f
  		@activity = Activity.create(desc: params[:desc], kind: params[:kind], amount: amount, user_id: session[:user_id])
  	end

    if @activity.save
      flash[:success] = "Check out your new activity!"
      user = User.find(session[:user_id]);
      user.update(balance: user.balance+amount);
      redirect_to activities_path
    else 
      flash[:error] = "Hmm, please check your inputs."
      redirect_to activities_payment_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate
  
  private
    def authenticate
      if !session[:user_id]
        redirect_to new_session_path
      end
    end
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  def show 
  	@payees = Payee.all
  end

  def new
  end

  def create
  	@payee = Payee.create(name: params[:name], email: params[:email], user_id: session[:user_id])
    if @payee.save
      flash[:success] = "Payee added!"
      redirect_to activities_payment_path
    else 
      flash[:error] = "Please fill out all input fields."
      redirect_to new_payees_path
    end
  end

  def edit
  	@payee = Payee.find(params[:format])
  end

  def update
  	@payee = Payee.find(params[:id])
  	@payee.update(name: params[:name], email: params[:email])
  	redirect_to payees_path
  end

  def destroy 
  	@payee = Payee.find(params[:format])
  	@payee.destroy
  	redirect_to payees_path
  end
end

  

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
  end

  def new
  end

  def destroy
  end
end

# Evans-MacBook-Pro:citylink sleepylemur$ rake routes
#      Prefix Verb   URI Pattern            Controller#Action
#     session POST   /session(.:format)     sessions#create
# new_session GET    /session/new(.:format) sessions#new
#             DELETE /session(.:format)     sessions#destroy
#        user POST   /user(.:format)        users#create
# Evans-MacBook-Pro:citylink sleepylemur$ rake routes
#      Prefix Verb   URI Pattern            Controller#Action
#        root GET    /                      session#new
#     session POST   /session(.:format)     sessions#create
# new_session GET    /session/new(.:format) sessions#new
#             DELETE /session(.:format)     sessions#destroy
#        user POST   /user(.:format)        users#create

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:username] = user.name
      redirect_to user_path
    else
      @email = params[:email]
      @error = "Unknown password/user"
      render :new
    end
  end

  def new
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
  end
end



# Evans-MacBook-Pro:citylink sleepylemur$ rake routes
#      Prefix Verb   URI Pattern            Controller#Action
#     session POST   /session(.:format)     sessions#create
# new_session GET    /session/new(.:format) sessions#new
#             DELETE /session(.:format)     sessions#destroy
#        user POST   /user(.:format)        users#create
# Evans-MacBook-Pro:citylink sleepylemur$ rake routes
#      Prefix Verb   URI Pattern            Controller#Action
#        root GET    /                      session#new
#     session POST   /session(.:format)     sessions#create
# new_session GET    /session/new(.:format) sessions#new
#             DELETE /session(.:format)     sessions#destroy
#        user POST   /user(.:format)        users#create

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  def create
    if params[:password] != params[:password_confirmation]
      @name = params[:name]
      @email = params[:email]
      @error = "Passwords don't match"
      render :new
      return
    end
    user = User.create(name: params[:name],email: params[:email], password: params[:password])

    if user.save
      flash[:success] = "Welcome to Citylink!"
      session[:user_id] = user.id
      session[:username] = user.name
      redirect_to user_path
    else 
      flash[:error] = "Hmm, please check your inputs."
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/depositform.html.erb
<div class="centered-form">
<h1>Make a Deposit</h1>
<form class="pure-form pure-form-stacked" action="/activities" method="POST">
<fieldset>
  <label for="kind">Deposit Type: </label>
  <select name="kind">
    <option value="check">check</option>
    <option value="cash">cash</option>
  </select>
  <label for="desc">Description: </label>
  <input name="desc" type="text">
  <label for="deposit">Amount: </label>
  <input name="deposit" type="text">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>">

  <button class="pure-button pure-button-primary">Deposit</button>
  </fieldset>
</form> 
</div>

app/views/activities/paymentform.html.erb
<div class="centered-form">
<h1>Make a Payment</h1>
<%= link_to "Add a Payee", new_payees_path %>
<form class="pure-form pure-form-stacked" action="/activities" method="POST">
<fieldset>
  <label for="kind">Payee: </label>
  <select name="kind">
    <% @payees.each do |payee| %>
    <option><%= payee.name %></option>
    <% end %>
  </select>
  <label for="desc">Description: </label>
  <input name="desc" type="text">
  <label for="payment">Amount</label>
  <input name="payment" type="text">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>">

  <button class="pure-button pure-button-primary">Pay</button>
  </fieldset>
</form> 
</div>

app/views/activities/show.html.erb
<table class="activity-table">
<thead>
<tr>
  <th>Date</th>
  <th>Type</th>
  <th>Description</th>
  <th>Amount</th>
</tr>
</thead>
<tbody>
<% sum = 0 %>
<% @activities.each do |activity| %>
	<tr>
	  <td><%= activity.created_at.strftime("%m/%d/%Y") %></td>
    <td><%= activity.kind %></td>
    <td><%= activity.desc %></td>
    <td class="alignright <%= "debt" if activity.amount < 0 %>"><%= "$%.2f" % activity.amount %></td>
    <% sum += activity.amount %>
  </tr>
<% end %>
</tbody>
<tfoot>
  <tr>
    <td></td>
    <td></td>
    <td>Balance:</td>
    <td class="alignright <%= "debt" if sum < 0 %>"><%= "$%.2f" % sum %></td>
  </tr>
</tfoot>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citylink</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	Citylink
</header>
<nav>
  <% if !session[:user_id] %>
    <%= link_to "New User", new_user_path %>
    <%= link_to "Sign In", new_session_path %>
  <% end %>
  <% if session[:user_id] %>
	  <%= link_to "Home", user_path %>
	  <%= link_to "Logout", session_path, method: :delete %>
  
      <a style="color: black">Welcome, <%= session[:username] %>!</a>
  <% end %>
</nav>

<% if flash %>
	<% flash.each do |key, value| %>
		<div class="alert-alert-<%= key %>"><%= value %></div>
	<% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/payees/_form.html.erb
<div class="centered-form">
<% if @error %>
  <h3 style = "color: red"><%= @error %></h3>
<% end %>

<form class="pure-form pure-form-stacked" action="/payees" method="POST">
<fieldset>
<label for="name">Name: </label>
  <input name="name" type="text" >
  <label for="email">Email: </label>
  <input name="email" type="email" >
  <input name="authenticity_token" value="<%= form_authenticity_token() %>" type = "hidden">
  <button class="pure-button pure-button-primary">Submit</button>
  </fieldset>
</form> 
</div>

app/views/payees/edit.html.erb
<div class="centered-form">
<h1>Edit Payee: </h1>
<% if @error %>
  <h3 style = "color: red"><%= @error %></h3>
<% end %>

<form class="pure-form pure-form-stacked" action="/payees" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="id" value="<%= @payee.id %>">
<fieldset>
<label for="name">Name: </label>
  <input name="name" type="text" value="<%= @payee.name %>">
  <label for="email">Email: </label>
  <input name="email" type = "text" value="<%= @payee.email %>">
  <input name="authenticity_token" value="<%= form_authenticity_token() %>" type = "hidden">
  <button class="pure-button pure-button-primary">Submit</button>
  </fieldset>
</form> 
</div>

app/views/payees/index.html.erb
<h1>All Payees</h1>
	<% @payees.each do |payee| %>
	<li><%= link_to payee.name, payee %></li>
<% end %>

app/views/payees/new.html.erb
<h1 class='centered-form'>New Payee: </h1>
<%= render 'form' %>

app/views/payees/show.html.erb
<div class="centered-form">
<h1>All Payees</h1>
	<% @payees.each do |payee| %>
	<li><%= payee.name %> <%= payee.email %>
	<%= link_to "edit", edit_payees_path(payee.id) %>
	<%= link_to "delete", payees_path(payee.id), method: :delete %>
	</li>
<% end %>
</div>

app/views/session/signin.html.erb
<% if @error %>
  <h3 style = "color: red"><%= @error %></h3>
<% end %>
<h1>Sign In: </h1>
<form class="pure-form pure-form-stacked" action="/session" method="POST">
<fieldset>
  <label for="email">Email: </label>
  <input name="email" type="text">
  <label for="password">Password</label>
  <input name="password" type="password">
  <input name="authenticity_token" value="<%= form_authenticity_token() %>" type = "hidden">
  <button class="pure-button pure-button-primary">Sign In</button>
  </fieldset>
</form>

app/views/users/new.html.erb
<div class="centered-form">
<% if @error %>
  <h3 style = "color: red"><%= @error %></h3>
<% end %>
<h1>Sign Up: </h1>
<form class="pure-form pure-form-stacked" action="/user" method="POST">
<fieldset>
<label for="name">Username: </label>
  <input name="name" type="text" placeholder="4 to 20 characters long">
  <label for="email">Email: </label>
  <input name="email" type="email">
  <label for="password">Password</label>
  <input name="password" type="password">
  <label for="password_confirmation">Confirm Password</label>
  <input name="password_confirmation" type="password">
  <input name="authenticity_token" value="<%= form_authenticity_token() %>" type = "hidden">
  <button class="pure-button pure-button-primary">Sign Up</button>
  </fieldset>
</form> 
</div>

app/views/users/show.html.erb
<h2 id="user-home">What would you like to do today?</h2>
<div class="centered-form">
Current balance: <%= "$%.2f" % @user.balance %>
<ul class='happybuttons'>
	<li><%= link_to "Add a Payee", new_payees_path %></li>
	<li><%= link_to "See All Payees", payees_path %></li>
	<li><%= link_to "See Activity", activities_path %></li>
	<li><%= link_to "Make a Deposit", activities_deposit_path %></li>
	<li><%= link_to "Make a Payment", activities_payment_path %></li>
</ul>
</div>